/*
 * main.c - ForgeOS Flight Simulator Control and Monitoring System
 *          Team 3 | Section 9   (OSSP / Operating Systems project)
 *
 * The flight data is SYNTHETIC telemetry generated by our simulator
 * processes. It is NOT live data from real aircraft.
 *
 * Process model
 * -------------
 *   PARENT CONTROLLER (single-threaded event loop)
 *     |-- fork() -> FS101 child  \
 *     |-- fork() -> FS202 child   |  every child write()s IpcMessage records
 *     |-- ...                     |  into ONE anonymous pipe
 *     `-- fork() -> FS606 child  /
 *
 *   The parent select()s on two sources at once, so it never blocks on one:
 *     1. read end of the pipe  (telemetry from the children)
 *     2. listening TCP socket  (browser / HTTP API connections)
 *
 * Shutdown: SIGINT/SIGTERM (or GET /api/stop) -> flag set -> parent sends
 * SIGTERM to every child -> waitpid() reaps every child -> resources closed.
 */

#define _POSIX_C_SOURCE 200809L

#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <signal.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include "common.h"

/* ------------------------------------------------------------------ */
/* Global state                                                        */
/* ------------------------------------------------------------------ */

typedef struct {
    pid_t         pid;
    int           alive;      /* child still running (not yet reaped) */
    int           has_data;   /* at least one packet received         */
    unsigned long packets;
    Telemetry     last;
    Telemetry     history[60];
    unsigned int  history_count;
    unsigned int  history_head;
} FlightState;

static FlightState g_flights[NUM_FLIGHTS];
static unsigned long g_total_packets = 0;
static time_t g_start_time;
static int g_log_fd = -1;
static int g_listen_fd = -1;
static int g_pipe_fd[2] = { -1, -1 };
static int g_pipe_open = 0;

/* Only async-signal-safe data is touched inside signal handlers. */
static volatile sig_atomic_t g_shutdown = 0;
static volatile sig_atomic_t g_last_signal = 0;   /* 0 = HTTP /api/stop */
static volatile sig_atomic_t g_child_stop = 0;    /* used in child only */

/* ------------------------------------------------------------------ */
/* Small helpers                                                       */
/* ------------------------------------------------------------------ */

static int write_all(int fd, const void *buf, size_t len)
{
    const char *p = buf;
    while (len > 0) {
        ssize_t n = write(fd, p, len);
        if (n < 0) {
            if (errno == EINTR) continue;
            return -1;
        }
        p += n;
        len -= (size_t)n;
    }
    return 0;
}

static void timestamp(char *out, size_t n)
{
    time_t now = time(NULL);
    struct tm tm;
    localtime_r(&now, &tm);
    strftime(out, n, "%Y-%m-%d %H:%M:%S", &tm);
}

static const char *status_text(const Telemetry *t)
{
    if (t->emergency) return "EMERGENCY";
    if (t->altitude_warning && t->fuel_warning) return "ALTITUDE + LOW FUEL";
    if (t->altitude_warning) return "ALTITUDE WARNING";
    if (t->fuel_warning) return "LOW FUEL";
    return "NORMAL";
}

/* ------------------------------------------------------------------ */
/* Signal handlers (only set flags - nothing else is async-signal-safe) */
/* ------------------------------------------------------------------ */

static void parent_signal_handler(int sig)
{
    g_last_signal = sig;
    g_shutdown = 1;
}

static void child_term_handler(int sig)
{
    (void)sig;
    g_child_stop = 1;
}

static int install_handler(int sig, void (*fn)(int))
{
    struct sigaction sa;
    memset(&sa, 0, sizeof sa);
    sa.sa_handler = fn;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;   /* no SA_RESTART: blocking calls return EINTR */
    return sigaction(sig, &sa, NULL);
}

/* ------------------------------------------------------------------ */
/* Flight (child) process                                              */
/* ------------------------------------------------------------------ */

/* Approximately normal noise, mean 0, sd ~0.58 (sum of 4 uniforms). */
static double noise(unsigned *seed)
{
    double s = 0.0;
    for (int i = 0; i < 4; i++) s += (double)rand_r(seed) / (double)RAND_MAX;
    return s - 2.0;
}

static double clampd(double v, double lo, double hi)
{
    return v < lo ? lo : (v > hi ? hi : v);
}

/* Runs inside the forked child. Never returns. */
static void flight_process(int idx, int wfd, double burn_mult)
{
    const FlightConfig *cfg = &FLIGHT_TABLE[idx];

    /* Children ignore Ctrl+C (the terminal sends SIGINT to the whole
     * foreground process group); the PARENT decides when they stop and
     * asks them with SIGTERM. */
    install_handler(SIGINT, SIG_IGN);
    install_handler(SIGTERM, child_term_handler);

    char msg[128];
    int len = snprintf(msg, sizeof msg,
                       "  [child] %s started: getpid()=%d getppid()=%d\n",
                       cfg->id, (int)getpid(), (int)getppid());
    if (len > 0) (void)write_all(STDOUT_FILENO, msg, (size_t)len);

    unsigned seed = (unsigned)time(NULL) ^ ((unsigned)getpid() * 2654435761u);
    double alt = cfg->start_alt, speed = cfg->start_speed, fuel = 100.0;
    int tick = 0;

    struct timespec next;
    clock_gettime(CLOCK_MONOTONIC, &next);

    while (!g_child_stop) {
        tick++;

        if (fuel > 0.0) {
            /* mean-reverting random walk => smooth, natural fluctuation */
            alt   += (10000.0 - alt) * 0.03 + noise(&seed) * 130.0;
            speed += (440.0 - speed) * 0.05 + noise(&seed) * 14.0;
            alt   = clampd(alt, 9000.0, 11000.0);
            speed = clampd(speed, 350.0, 520.0);
            double u = (double)rand_r(&seed) / (double)RAND_MAX;
            fuel -= cfg->burn_rate * burn_mult * (0.9 + 0.2 * u);
            if (fuel < 1.0) fuel = 0.0;          /* tank empty */
        } else {
            /* Out of fuel: engine off, emergency glide/descent. */
            alt   = clampd(alt - 250.0, 0.0, 11000.0);
            speed = clampd(speed - 25.0, 0.0, 520.0);
        }

        IpcMessage m;
        memset(&m, 0, sizeof m);
        m.flight_index = idx;
        m.pid = getpid();
        m.data.tick = tick;
        m.data.altitude = (int)alt;
        m.data.airspeed = (int)speed;
        m.data.fuel = (int)fuel;
        m.data.engine_on = fuel > 0.0;
        m.data.altitude_warning =
            (m.data.altitude < ALT_WARN_LOW || m.data.altitude > ALT_WARN_HIGH);
        m.data.fuel_warning = (m.data.fuel <= FUEL_LOW_PCT);
        m.data.emergency = (m.data.fuel <= FUEL_EMERGENCY_PCT);

        /* One atomic write() (size << PIPE_BUF) into the shared pipe. */
        ssize_t n;
        do {
            n = write(wfd, &m, sizeof m);
        } while (n < 0 && errno == EINTR && !g_child_stop);
        if (n != (ssize_t)sizeof m) break;   /* parent gone or shutdown */

        /* Sleep until an absolute deadline => 1 tick/s without drift. */
        next.tv_sec += 1;
        int r;
        do {
            r = clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &next, NULL);
        } while (r == EINTR && !g_child_stop);
    }

    close(wfd);
    _exit(0);   /* _exit: do not flush the parent's inherited stdio buffers */
}

/* ------------------------------------------------------------------ */
/* Logging (POSIX open/write, O_APPEND)                                */
/* ------------------------------------------------------------------ */

static int open_log(void)
{
    if (mkdir("logs", 0755) < 0 && errno != EEXIST) {
        perror("mkdir logs");
        return -1;
    }
    g_log_fd = open(LOG_PATH, O_WRONLY | O_CREAT | O_APPEND, 0644);
    if (g_log_fd < 0) {
        perror("open " LOG_PATH);
        return -1;
    }
    char ts[32], line[160];
    timestamp(ts, sizeof ts);
    int n = snprintf(line, sizeof line,
                     "# --- session start %s | controller PID %d | synthetic telemetry ---\n",
                     ts, (int)getpid());
    if (write_all(g_log_fd, line, (size_t)n) < 0) perror("write log");
    return 0;
}

static void log_telemetry(int idx, pid_t pid, const Telemetry *t)
{
    char ts[32], line[256];
    timestamp(ts, sizeof ts);
    int n = snprintf(line, sizeof line,
                     "%s | %s | PID %d | TICK %d | ALT %d ft | SPD %d km/h | "
                     "FUEL %d%% | ENGINE %s | %s\n",
                     ts, FLIGHT_TABLE[idx].id, (int)pid, t->tick, t->altitude,
                     t->airspeed, t->fuel, t->engine_on ? "ON" : "OFF",
                     status_text(t));
    if (n > 0 && write_all(g_log_fd, line, (size_t)n) < 0) perror("write log");
}

/* ------------------------------------------------------------------ */
/* Pipe (telemetry) handling in the parent                             */
/* ------------------------------------------------------------------ */

static void handle_pipe(void)
{
    static unsigned char buf[sizeof(IpcMessage) * 16];
    static size_t have = 0;

    ssize_t n = read(g_pipe_fd[0], buf + have, sizeof buf - have);
    if (n < 0) {
        if (errno != EINTR && errno != EAGAIN) perror("read pipe");
        return;
    }
    if (n == 0) {                       /* every writer has exited */
        g_pipe_open = 0;
        if (!g_shutdown) fprintf(stderr, "controller: pipe closed (all flights ended)\n");
        return;
    }
    have += (size_t)n;

    size_t off = 0;
    while (have - off >= sizeof(IpcMessage)) {
        IpcMessage m;
        memcpy(&m, buf + off, sizeof m);
        off += sizeof m;
        if (m.flight_index < 0 || m.flight_index >= NUM_FLIGHTS) continue;

        FlightState *f = &g_flights[m.flight_index];
        f->last = m.data;
        f->has_data = 1;
        f->history[f->history_head] = m.data;
        f->history_head = (f->history_head + 1U) % 60U;
        if (f->history_count < 60U) f->history_count++;
        f->packets++;
        g_total_packets++;

        printf("[%s | PID %d] TICK %03d | ALT=%d ft | SPEED=%d km/h | FUEL=%d%% | %s\n",
               FLIGHT_TABLE[m.flight_index].id, (int)m.pid, m.data.tick,
               m.data.altitude, m.data.airspeed, m.data.fuel,
               status_text(&m.data));
        log_telemetry(m.flight_index, m.pid, &m.data);
    }
    memmove(buf, buf + off, have - off);
    have -= off;
    fflush(stdout);
}

/* ------------------------------------------------------------------ */
/* Child monitoring                                                    */
/* ------------------------------------------------------------------ */

static int find_flight(pid_t pid)
{
    for (int i = 0; i < NUM_FLIGHTS; i++)
        if (g_flights[i].pid == pid) return i;
    return -1;
}

static void describe_status(int status, char *out, size_t n)
{
    if (WIFEXITED(status))
        snprintf(out, n, "exited with code %d", WEXITSTATUS(status));
    else if (WIFSIGNALED(status))
        snprintf(out, n, "killed by signal %d", WTERMSIG(status));
    else
        snprintf(out, n, "status 0x%x", status);
}

/* Non-blocking sweep: notice children that died on their own. */
static void monitor_children(void)
{
    int status;
    pid_t pid;
    while ((pid = waitpid(-1, &status, WNOHANG)) > 0) {
        int i = find_flight(pid);
        if (i < 0) continue;
        char d[64];
        describe_status(status, d, sizeof d);
        g_flights[i].alive = 0;
        printf("[MONITOR] %s (PID %d) %s unexpectedly - reaped with waitpid()\n",
               FLIGHT_TABLE[i].id, (int)pid, d);
        fflush(stdout);
    }
}

/* ------------------------------------------------------------------ */
/* HTTP server                                                         */
/* ------------------------------------------------------------------ */

static int setup_server(void)
{
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if (fd < 0) { perror("socket"); return -1; }

    int one = 1;
    if (setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &one, sizeof one) < 0)
        perror("setsockopt SO_REUSEADDR");

    struct sockaddr_in addr;
    memset(&addr, 0, sizeof addr);
    addr.sin_family = AF_INET;
    addr.sin_port = htons(HTTP_PORT);
    if (inet_pton(AF_INET, HTTP_BIND_ADDR, &addr.sin_addr) != 1) {
        fprintf(stderr, "inet_pton failed\n");
        close(fd);
        return -1;
    }
    if (bind(fd, (struct sockaddr *)&addr, sizeof addr) < 0) {
        perror("bind (is port 8080 already in use?)");
        close(fd);
        return -1;
    }
    if (listen(fd, 16) < 0) { perror("listen"); close(fd); return -1; }
    return fd;
}

static void send_response(int cfd, const char *status, const char *ctype,
                          const char *body, size_t len)
{
    char hdr[256];
    int n = snprintf(hdr, sizeof hdr,
                     "HTTP/1.1 %s\r\nContent-Type: %s\r\nContent-Length: %zu\r\n"
                     "Cache-Control: no-store\r\nConnection: close\r\n\r\n",
                     status, ctype, len);
    if (n < 0 || write_all(cfd, hdr, (size_t)n) < 0) return;
    if (len > 0) (void)write_all(cfd, body, len);
}

static void jappend(char *buf, size_t cap, size_t *off, const char *fmt, ...)
{
    if (*off >= cap) return;
    va_list ap;
    va_start(ap, fmt);
    int n = vsnprintf(buf + *off, cap - *off, fmt, ap);
    va_end(ap);
    if (n < 0) return;
    *off += (size_t)n;
    if (*off > cap) *off = cap;
}

static void build_json(char *buf, size_t cap)
{
    size_t off = 0;
    jappend(buf, cap, &off,
            "{\"backend\":\"online\",\"controller_pid\":%d,\"flight_count\":%d,"
            "\"total_packets\":%lu,\"uptime_seconds\":%ld,"
            "\"shutdown_requested\":%s,\"synthetic\":true,\"history_size\":60,\"flights\":[",
            (int)getpid(), NUM_FLIGHTS, g_total_packets,
            (long)(time(NULL) - g_start_time), g_shutdown ? "true" : "false");

    for (int i = 0; i < NUM_FLIGHTS; i++) {
        const FlightState *f = &g_flights[i];
        const Telemetry *t = &f->last;
        const char *status = !f->alive ? "OFFLINE"
                           : !f->has_data ? "WAITING"
                           : status_text(t);
        jappend(buf, cap, &off,
                "%s{\"id\":\"%s\",\"name\":\"%s\",\"pid\":%d,\"alive\":%s,"
                "\"has_data\":%s,\"tick\":%d,\"altitude\":%d,\"airspeed\":%d,"
                "\"fuel\":%d,\"engine\":\"%s\",\"status\":\"%s\","
                "\"altitude_warning\":%s,\"fuel_warning\":%s,\"emergency\":%s,"
                "\"packets\":%lu,\"history\":[",
                i ? "," : "", FLIGHT_TABLE[i].id, FLIGHT_TABLE[i].name,
                (int)f->pid, f->alive ? "true" : "false",
                f->has_data ? "true" : "false", t->tick, t->altitude,
                t->airspeed, t->fuel, t->engine_on ? "ON" : "OFF", status,
                t->altitude_warning ? "true" : "false",
                t->fuel_warning ? "true" : "false",
                t->emergency ? "true" : "false", f->packets);
        unsigned int start = f->history_count == 60U ? f->history_head : 0U;
        for (unsigned int j = 0; j < f->history_count; ++j) {
            unsigned int idx = (start + j) % 60U;
            const Telemetry *h = &f->history[idx];
            jappend(buf, cap, &off,
                    "%s{\"tick\":%d,\"altitude\":%d,\"airspeed\":%d,\"fuel\":%d}",
                    j ? "," : "", h->tick, h->altitude, h->airspeed, h->fuel);
        }
        jappend(buf, cap, &off, "]}");
    }
    jappend(buf, cap, &off, "]}");
}

static char *read_file(const char *path, size_t *len)
{
    int fd = open(path, O_RDONLY);
    if (fd < 0) return NULL;
    struct stat st;
    if (fstat(fd, &st) < 0 || st.st_size <= 0) { close(fd); return NULL; }
    char *buf = malloc((size_t)st.st_size);
    if (!buf) { close(fd); return NULL; }
    size_t got = 0;
    while (got < (size_t)st.st_size) {
        ssize_t n = read(fd, buf + got, (size_t)st.st_size - got);
        if (n < 0 && errno == EINTR) continue;
        if (n <= 0) break;
        got += (size_t)n;
    }
    close(fd);
    *len = got;
    return buf;
}

/* Look for web/index.html in the CWD, then next to the executable. */
static char *load_index(size_t *len)
{
    char *html = read_file(WEB_INDEX, len);
    if (html) return html;

    char exe[512];
    ssize_t n = readlink("/proc/self/exe", exe, sizeof exe - 32);
    if (n <= 0) return NULL;
    exe[n] = '\0';
    char *slash = strrchr(exe, '/');
    if (!slash) return NULL;
    strcpy(slash, "/web/index.html");
    return read_file(exe, len);
}

static char *read_tail(const char *path, size_t max_bytes, size_t *out_len)
{
    int fd = open(path, O_RDONLY);
    if (fd < 0) return NULL;
    struct stat st;
    if (fstat(fd, &st) < 0) { close(fd); return NULL; }
    off_t size = st.st_size;
    off_t start = size > (off_t)max_bytes ? size - (off_t)max_bytes : 0;
    if (lseek(fd, start, SEEK_SET) < 0) { close(fd); return NULL; }
    size_t want = (size_t)(size - start);
    char *buf = malloc(want + 1);
    if (!buf) { close(fd); return NULL; }
    size_t got = 0;
    while (got < want) {
        ssize_t n = read(fd, buf + got, want - got);
        if (n < 0 && errno == EINTR) continue;
        if (n <= 0) break;
        got += (size_t)n;
    }
    close(fd);
    buf[got] = '\0';
    *out_len = got;
    return buf;
}

static void handle_http(void)
{
    int cfd;
    do {
        cfd = accept(g_listen_fd, NULL, NULL);
    } while (cfd < 0 && errno == EINTR && !g_shutdown);
    if (cfd < 0) {
        if (errno != EINTR && errno != EAGAIN && errno != ECONNABORTED)
            perror("accept");
        return;
    }

    /* Timeouts so a stalled client can never freeze the controller. */
    struct timeval to = { 1, 0 };
    setsockopt(cfd, SOL_SOCKET, SO_RCVTIMEO, &to, sizeof to);
    setsockopt(cfd, SOL_SOCKET, SO_SNDTIMEO, &to, sizeof to);

    char req[2048];
    ssize_t n;
    do {
        n = read(cfd, req, sizeof req - 1);
    } while (n < 0 && errno == EINTR);
    if (n <= 0) { close(cfd); return; }
    req[n] = '\0';

    char method[8], path[256];
    if (sscanf(req, "%7s %255s", method, path) != 2) {
        send_response(cfd, "400 Bad Request", "text/plain", "Bad Request\n", 12);
        close(cfd);
        return;
    }
    char *q = strchr(path, '?');
    if (q) *q = '\0';

    if (strcmp(method, "GET") != 0) {
        send_response(cfd, "405 Method Not Allowed", "text/plain",
                      "Method Not Allowed\n", 19);
    } else if (strcmp(path, "/") == 0 || strcmp(path, "/index.html") == 0) {
        size_t len = 0;
        char *html = load_index(&len);
        if (html) {
            send_response(cfd, "200 OK", "text/html; charset=utf-8", html, len);
            free(html);
        } else {
            const char *e = "web/index.html not found - run from the project directory\n";
            send_response(cfd, "500 Internal Server Error", "text/plain", e, strlen(e));
        }
    } else if (strcmp(path, "/api/state") == 0) {
        static char json[65536];
        build_json(json, sizeof json);
        send_response(cfd, "200 OK", "application/json", json, strlen(json));
    } else if (strcmp(path, "/api/logs") == 0) {
        size_t len = 0;
        char *logs = read_tail(LOG_PATH, 50000, &len);
        if (logs) {
            send_response(cfd, "200 OK", "text/plain; charset=utf-8", logs, len);
            free(logs);
        } else {
            const char *e = "No telemetry log available yet.\n";
            send_response(cfd, "200 OK", "text/plain; charset=utf-8", e, strlen(e));
        }
    } else if (strcmp(path, "/api/stop") == 0) {
        const char *ok = "{\"status\":\"shutting_down\"}";
        send_response(cfd, "200 OK", "application/json", ok, strlen(ok));
        g_last_signal = 0;
        g_shutdown = 1;
        printf("\n[HTTP] /api/stop received - graceful shutdown requested\n");
        fflush(stdout);
    } else if (strcmp(path, "/favicon.ico") == 0) {
        send_response(cfd, "204 No Content", "image/x-icon", "", 0);
    } else {
        send_response(cfd, "404 Not Found", "text/plain", "Not Found\n", 10);
    }
    close(cfd);
}

/* ------------------------------------------------------------------ */
/* Controlled shutdown: SIGTERM + waitpid() for every child            */
/* ------------------------------------------------------------------ */

static void reap_flight(int i)
{
    pid_t pid = g_flights[i].pid;
    int status = 0;
    pid_t r = 0;
    char d[64];

    for (int tries = 0; tries < 60; tries++) {          /* wait up to ~3 s */
        r = waitpid(pid, &status, WNOHANG);
        if (r == pid) goto reaped;
        if (r < 0) {
            if (errno == EINTR) continue;
            if (errno == ECHILD) { g_flights[i].alive = 0; return; }
            perror("waitpid");
            break;
        }
        struct timespec ts = { 0, 50000000L };
        nanosleep(&ts, NULL);
    }
    fprintf(stderr, "controller: %s did not stop, sending SIGKILL\n", FLIGHT_TABLE[i].id);
    kill(pid, SIGKILL);
    do {
        r = waitpid(pid, &status, 0);
    } while (r < 0 && errno == EINTR);

reaped:
    describe_status(status, d, sizeof d);
    printf("  waitpid() reaped %s | PID %d | %s\n", FLIGHT_TABLE[i].id, (int)pid, d);
    g_flights[i].alive = 0;
}

static void shutdown_children(void)
{
    for (int i = 0; i < NUM_FLIGHTS; i++) {
        if (g_flights[i].pid > 0 && g_flights[i].alive) {
            if (kill(g_flights[i].pid, SIGTERM) < 0) {
                if (errno != ESRCH) perror("kill");
            } else {
                printf("  kill(%d, SIGTERM) -> %s\n", (int)g_flights[i].pid,
                       FLIGHT_TABLE[i].id);
            }
        }
    }
    for (int i = 0; i < NUM_FLIGHTS; i++)
        if (g_flights[i].pid > 0 && g_flights[i].alive) reap_flight(i);
}

/* ------------------------------------------------------------------ */
/* main                                                                */
/* ------------------------------------------------------------------ */

int main(int argc, char **argv)
{
    double burn_mult = 1.0;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--demo") == 0) {
            burn_mult = 8.0;
        } else {
            fprintf(stderr, "usage: %s [--demo]\n  --demo  fuel burns 8x faster\n", argv[0]);
            return 2;
        }
    }
    g_start_time = time(NULL);

    if (install_handler(SIGINT, parent_signal_handler) < 0 ||
        install_handler(SIGTERM, parent_signal_handler) < 0) {
        perror("sigaction");
        return 1;
    }
    install_handler(SIGPIPE, SIG_IGN);   /* a closed browser socket must not kill us */

    if (open_log() < 0) return 1;
    g_listen_fd = setup_server();
    if (g_listen_fd < 0) { close(g_log_fd); return 1; }
    if (pipe(g_pipe_fd) < 0) {
        perror("pipe");
        close(g_listen_fd);
        close(g_log_fd);
        return 1;
    }
    g_pipe_open = 1;

    printf("=============================================\n");
    printf(" ForgeOS | Flight Simulator Control System\n");
    printf(" Team 3 | Section 9\n");
    printf("=============================================\n");
    printf("Controller PID: %d\n", (int)getpid());
    printf("Flights: %d\n", NUM_FLIGHTS);
    printf("Telemetry: continuous, 1 tick/sec/flight (SYNTHETIC data)%s\n",
           burn_mult > 1.0 ? " [demo: fast fuel burn]" : "");
    printf("Application: http://%s:%d\n", HTTP_BIND_ADDR, HTTP_PORT);
    printf("IPC: anonymous pipe() | Signals: SIGINT/SIGTERM\n\n");
    printf("Flight process created:\n");

    for (int i = 0; i < NUM_FLIGHTS; i++) {
        fflush(stdout);                    /* avoid duplicated buffered output in child */
        pid_t pid = fork();
        if (pid < 0) {
            perror("fork");
            g_shutdown = 1;
            break;
        }
        if (pid == 0) {
            /* CHILD: close what it does not need, then simulate. */
            close(g_pipe_fd[0]);           /* read end belongs to the parent */
            close(g_listen_fd);
            close(g_log_fd);
            flight_process(i, g_pipe_fd[1], burn_mult);
            _exit(1);                      /* not reached */
        }
        g_flights[i].pid = pid;
        g_flights[i].alive = 1;
        printf("%s | PID %d\n", FLIGHT_TABLE[i].id, (int)pid);
    }
    close(g_pipe_fd[1]);                   /* parent only reads */
    printf("\n");
    fflush(stdout);

    while (!g_shutdown) {
        monitor_children();

        fd_set rfds;
        FD_ZERO(&rfds);
        FD_SET(g_listen_fd, &rfds);
        int maxfd = g_listen_fd;
        if (g_pipe_open) {
            FD_SET(g_pipe_fd[0], &rfds);
            if (g_pipe_fd[0] > maxfd) maxfd = g_pipe_fd[0];
        }

        struct timeval tv = { 0, 500000 };   /* wake twice/s to re-check flags */
        int r = select(maxfd + 1, &rfds, NULL, NULL, &tv);
        if (r < 0) {
            if (errno == EINTR) continue;    /* a signal arrived: re-check flag */
            perror("select");
            break;
        }
        if (r == 0) continue;
        if (g_pipe_open && FD_ISSET(g_pipe_fd[0], &rfds)) handle_pipe();
        if (FD_ISSET(g_listen_fd, &rfds)) handle_http();
    }

    /* ---------------- graceful shutdown ---------------- */
    printf("\n=============================================\n");
    if (g_last_signal == SIGINT)       printf(" SIGINT received - shutting down\n");
    else if (g_last_signal == SIGTERM) printf(" SIGTERM received - shutting down\n");
    else                               printf(" Shutdown requested - shutting down\n");
    printf("=============================================\n");
    shutdown_children();

    close(g_pipe_fd[0]);
    close(g_listen_fd);
    if (g_log_fd >= 0) {
        char line[96];
        int n = snprintf(line, sizeof line, "# --- session end | %lu packets ---\n",
                         g_total_packets);
        (void)write_all(g_log_fd, line, (size_t)n);
        close(g_log_fd);
    }
    printf("All %d flight processes reaped. Total telemetry packets: %lu\n",
           NUM_FLIGHTS, g_total_packets);
    printf("Log file: %s\nClean exit.\n", LOG_PATH);
    return 0;
}
